In [ ]:
pip install requests

In [ ]:
import requests

url = "https://api.euron.one/api/v1/euri/embeddings"


headers = {
    
}
    "Content-Type": "application/json",
    "Authorization": "Bearer euri-cc3925dc19d652dcb0bd8aacaa7e3cb2fb7925101bf01ec565cf0b9e3cd66b4e"
}

data = {
    "input": "My name is Emkay.",
    "model": "text-embedding-3-small"
}

response = requests.post(url, headers=headers, json=data)

embedding1 = response.json()["data"][0]["embedding"]
print(embedding1,end="")


In [ ]:
len(embedding1) # is ia a 1536 vector of numbers.Each number is like a coordinate along one axis in that space. Together, all 1536 numbers pinpoint the semantic location of the sentence in high-dimensional space. No single number has “dimensions”; it’s just a coordinate value.

In [ ]:
 a= embedding1

In [5]:
import requests

url = "https://api.euron.one/api/v1/euri/embeddings"

headers = {
    "Content-Type": "application/json",
    "Authorization": "Bearer euri-cc3925dc19d652dcb0bd8aacaa7e3cb2fb7925101bf01ec565cf0b9e3cd66b4e"
}

data = {
    "input": "Emkay used to work for euron.",
    "model": "text-embedding-3-small"
}

response = requests.post(url, headers=headers, json=data)

embedding2 = response.json()["data"][0]["embedding"]
print(embedding2,end="")

[-0.022247907, 0.009728942, 0.010451746, -0.0043187537, 0.00031035396, 0.03160099, 0.029634964, 0.05741955, -0.010704727, -0.0065883584, -0.0055041523, -0.046143807, 0.01754968, 0.014542816, 0.021525104, 0.018012276, -0.04524753, 0.010090344, -0.04354171, 0.00022802207, 0.021264894, 0.041604597, 0.0035851079, 0.040332463, -0.008232738, -0.019573532, 0.019457884, 0.020932404, 0.0055149943, -0.05354532, 0.032959864, -0.025486069, 0.029042264, 0.0034025998, -0.003626669, -0.01847487, -0.004495841, 0.002322008, -0.00030290004, 0.020036127, 0.0074737933, 0.027191887, -0.041460037, 0.015236708, -0.04391757, -0.056783482, -0.08199488, 0.019501252, 0.06788575, 0.008464035, 0.005240329, 0.007603898, -0.020917948, 0.018865185, -0.034694593, 0.00017166595, 0.00013496105, -0.015207796, -0.016132984, 0.021452822, 0.05059628, 0.026960589, 0.009642205, 0.042818908, -0.038221873, -0.0017862293, -0.0328153, 0.016826877, -0.01762196, -0.0020383073, 0.04270326, 0.021235982, -0.021062508, 0.012844227, 0.0

In [6]:
b= embedding2

In [7]:
import requests

url = "https://api.euron.one/api/v1/euri/embeddings"

headers = {
    "Content-Type": "application/json",
    "Authorization": "Bearer euri-cc3925dc19d652dcb0bd8aacaa7e3cb2fb7925101bf01ec565cf0b9e3cd66b4e"
}

data = {
    "input": "Rakesh is GenAI batch student.",
    "model": "text-embedding-3-small"
}

response = requests.post(url, headers=headers, json=data)

embedding3 = response.json()["data"][0]["embedding"]
print(embedding3,end="")

[-0.009967171, -0.02802462, 0.046427634, -0.026845634, 0.003763945, -0.067432545, 0.0036453689, 0.04515379, -0.020828743, -0.05431464, -0.0174002, -0.07431674, -0.05274266, 0.0060778735, 0.021303048, -0.03935372, -0.047565967, -0.017996468, -0.0643428, 0.030192869, 0.011051295, 0.018213293, 0.08326077, -0.043798633, 0.03011156, -0.005054731, 0.048514575, 0.0062201647, 0.034935914, -0.01861984, -0.010997089, -0.027387697, -0.020259578, -0.04455752, -0.022495585, -0.013775158, -0.015557188, -0.017684782, -0.03176485, 0.001621105, 0.011329101, -0.01645159, -0.0408986, 0.069167145, 0.0056103445, 0.015259054, 0.005261392, -0.07030548, 0.06325867, 0.026181608, -0.04775569, 0.003181228, 0.032957386, 0.043039747, -0.017034307, 0.04046495, -0.0013907285, 0.010434699, 0.03935372, -0.021628285, 0.029569497, -0.0033167435, -0.006247268, 0.02948819, 0.0033455407, -0.014323996, -0.041278042, 0.025002623, -0.037483606, -0.012413226, -0.009032113, -0.00080123584, -0.03211719, -0.03341814, 0.001713425,

In [8]:
c= embedding3

In [9]:
import requests

url = "https://api.euron.one/api/v1/euri/embeddings"

headers = {
    "Content-Type": "application/json",
    "Authorization": "Bearer euri-cc3925dc19d652dcb0bd8aacaa7e3cb2fb7925101bf01ec565cf0b9e3cd66b4e"
}

data = {
    "input": "what emkay does?.",
    "model": "text-embedding-3-small"
}

response = requests.post(url, headers=headers, json=data)

inp = response.json()["data"][0]["embedding"]


In [10]:
a,b,c,inp

([0.016624164,
  -0.03505324,
  -0.03125343,
  0.017918475,
  -0.037356872,
  0.0040254225,
  -0.029424772,
  0.04020673,
  -0.0010122929,
  -0.0026064315,
  -0.008104281,
  -0.037665606,
  -0.011815031,
  -0.030849699,
  0.0077183624,
  0.022608863,
  -0.040966693,
  0.036098186,
  -0.014154289,
  0.022549491,
  0.031419672,
  -0.008341769,
  0.015365478,
  0.048566308,
  0.02944852,
  6.459026e-06,
  0.01968776,
  -0.0084308265,
  -0.035124484,
  -0.023475695,
  0.026693659,
  -0.025838701,
  0.04205914,
  -0.023511318,
  -0.0020171644,
  0.03443577,
  -0.07248136,
  -0.010686963,
  -0.041702904,
  0.0074511883,
  0.004316346,
  0.015709836,
  -0.000548449,
  0.04659516,
  -0.064454265,
  0.0011347476,
  -0.099839985,
  0.0013373547,
  0.099460006,
  -0.014854878,
  -0.023226334,
  0.04120418,
  -0.021991394,
  0.048305072,
  0.0075283716,
  -0.023499444,
  -0.020352727,
  -0.014938,
  -0.027881099,
  0.020067742,
  0.010033871,
  0.0437928,
  0.0060975063,
  0.01949777,
  -0.0182747

In [11]:
type(a)

list

In [12]:
# Covert list to numpy array
import numpy as np
a = np.array(a)
b= np.array(b)
c = np.array(c)
inp = np.array(inp)

In [13]:
a,b,c,inp

(array([ 0.01662416, -0.03505324, -0.03125343, ..., -0.0041887 ,
        -0.00358607, -0.01610169], shape=(1536,)),
 array([-0.02224791,  0.00972894,  0.01045175, ..., -0.00680881,
         0.00818937, -0.02677266], shape=(1536,)),
 array([-0.00996717, -0.02802462,  0.04642763, ..., -0.02320027,
         0.05195667, -0.0339602 ], shape=(1536,)),
 array([ 0.0044105 , -0.01223828,  0.04140313, ..., -0.00533902,
        -0.02193453, -0.00708191], shape=(1536,)))

In [14]:
# Calculate the distance between inp and a,b,c using np.linalg.norm
# np.linalg.norm(inp-a) is the distance between inp and a
# Euclidean distance is the square root of the sum of the squared differences between the coordinates of the two points.
dist_inp_a = np.linalg.norm(inp-a)
dist_inp_b = np.linalg.norm(inp-b)
dist_inp_c = np.linalg.norm(inp-c)


In [15]:
dist_inp_a , dist_inp_b, dist_inp_c
# Meaning the distance between inp and a is 0.727926605892479, the distance between inp and b is 0.8301453531143942, and the distance between inp and c is 1.2219153747459328

(np.float64(0.7278712459793797),
 np.float64(0.8301453531143942),
 np.float64(1.221872997978866))

In [16]:
closest = min(dist_inp_a, dist_inp_b, dist_inp_c)
print(closest)

0.7278712459793797
